apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-kafka
  template:
    metadata:
      labels:
        app: zookeeper-kafka
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:5.5.3
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
        - name: kafka
          image: confluentinc/cp-enterprise-kafka:5.5.3
          env:
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "localhost:2181"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_JMX_PORT
              value: "9991"
#          ports:
#            - containerPort: 9092


---

apiVersion: v1
kind: Service
metadata:
  name: kafka-srv
spec:
  selector:
    app: zookeeper-kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      name: kafka
